// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// qD_MLE
NumericVector qD_MLE(NumericVector q, NumericVector ai);
RcppExport SEXP _hiDIP_qD_MLE(SEXP qSEXP, SEXP aiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ai(aiSEXP);
    rcpp_result_gen = Rcpp::wrap(qD_MLE(q, ai));
    return rcpp_result_gen;
END_RCPP
}
// qDSub2
NumericVector qDSub2(double q, int f1, double A, const int n);
RcppExport SEXP _hiDIP_qDSub2(SEXP qSEXP, SEXP f1SEXP, SEXP ASEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type f1(f1SEXP);
    Rcpp::traits::input_parameter< double >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(qDSub2(q, f1, A, n));
    return rcpp_result_gen;
END_RCPP
}
// qDSub
NumericVector qDSub(double q, NumericVector Xi, const int n);
RcppExport SEXP _hiDIP_qDSub(SEXP qSEXP, SEXP XiSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q(qSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Xi(XiSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(qDSub(q, Xi, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hiDIP_qD_MLE", (DL_FUNC) &_hiDIP_qD_MLE, 2},
    {"_hiDIP_qDSub2", (DL_FUNC) &_hiDIP_qDSub2, 4},
    {"_hiDIP_qDSub", (DL_FUNC) &_hiDIP_qDSub, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hiDIP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
